dependencies:
- name: elasticsearch
  version: "0.1.6"
  # repository: https://raw.githubusercontent.com/komljen/helm-charts/master/charts/
  repository: file://../elasticsearch
- name: fluent-bit
  version: "1.3.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: elasticsearch-curator
  version: "1.0.1"
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kibana
  version: "2.0.0"
  repository: https://kubernetes-charts.storage.googleapis.com/
